# Dockerfile.dev
FROM golang:alpine

WORKDIR /app

# Install Air (hot reload)
RUN go install github.com/air-verse/air@latest

# Pre-cache modules (speeds up first run)
COPY go.mod go.sum ./
RUN go mod download

# App code (will be overridden by volume mount in compose)
COPY . .

EXPOSE 8080
CMD ["air", "-c", ".air.toml"]
